table cotacoes
	lineageTag: 61aa2f73-51cb-48af-8b0b-6001a71d49a9

	measure 'Cotação do dia' = ```
			AVERAGE(cotacoes[Cotacao]) 
			```
		displayFolder: Medidas
		lineageTag: ed166a76-5b4f-47b3-a314-83220fcaed2d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Moeda
		dataType: string
		displayFolder: Colunas
		lineageTag: 1d4f08e0-c01d-4634-ad4c-cc1cf359ae3b
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	column DataHora
		dataType: dateTime
		formatString: General Date
		displayFolder: Colunas
		lineageTag: afc2abd4-5075-46dc-9408-0a1d86e27202
		summarizeBy: none
		sourceColumn: DataHora

		annotation SummarizationSetBy = Automatic

	column Cotacao
		dataType: double
		displayFolder: Colunas
		lineageTag: c841b889-f01a-4aa2-b45c-997da0af46f0
		summarizeBy: average
		sourceColumn: Cotacao

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TipoBoletim
		dataType: string
		displayFolder: Colunas
		lineageTag: a81f8ee2-f18c-4d88-bfc2-cdf4650c367a
		summarizeBy: none
		sourceColumn: TipoBoletim

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: dd/mm/yyyy
		displayFolder: Colunas
		lineageTag: fd1e066a-7c91-49c6-b6e2-efb31188e0e7
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	partition cotacoes = m
		mode: import
		queryGroup: Fatos
		source = getCotacoes(data_inicial, data_final)

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

