table cotacoes
	lineageTag: 7e7d3ba8-6e26-48d8-92ff-b143c28392d6
	sourceLineageTag: [dbo].[cotacoes]

	measure 'Cotação do dia' = ```
			AVERAGE(cotacoes[Cotacao]) 
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Medidas
		lineageTag: 42063d73-8f19-4b9d-9bf7-1458a043830b

		changedProperty = Name

		changedProperty = FormatString

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Cotação corrigida' = ```
			
			
			VAR __DataCtx = MAX(calendario[Data]) 
			
			VAR __UltimaDataComCotacao = 
			    CALCULATE(
			        LASTNONBLANK(calendario[Data], [Cotação do dia]),
			        calendario[Data] <= __DataCtx
			    )
			
			RETURN
			    CALCULATE(
			        [Cotação do dia],
			        calendario[Data] = __UltimaDataComCotacao
			    )
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Medidas
		lineageTag: 4b651edb-9b89-4225-ad58-6e22162c5f1d

		changedProperty = Name

		changedProperty = FormatString

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Moeda
		dataType: string
		displayFolder: Colunas
		lineageTag: de94830c-e5dc-4db3-8d55-bcbaef882322
		sourceLineageTag: Moeda
		summarizeBy: none
		sourceColumn: Moeda

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

	column DataHoraCotacao
		dataType: dateTime
		formatString: General Date
		displayFolder: Colunas
		lineageTag: ab8e4b0a-d673-463e-970d-5501e01eb400
		sourceLineageTag: DataHoraCotacao
		summarizeBy: none
		sourceColumn: DataHoraCotacao

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

	column DataCotacao
		dataType: dateTime
		formatString: Short Date
		displayFolder: Colunas
		lineageTag: 931f3920-1b96-4441-a72d-2fae29618d95
		sourceLineageTag: DataCotacao
		summarizeBy: none
		sourceColumn: DataCotacao

		changedProperty = FormatString

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

	column Cotacao
		dataType: double
		displayFolder: Colunas
		lineageTag: c871a0bc-1036-40ce-ae72-86458453b86d
		sourceLineageTag: Cotacao
		summarizeBy: average
		sourceColumn: Cotacao

		changedProperty = SummarizeBy

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TipoBoletim
		dataType: string
		displayFolder: Colunas
		lineageTag: 04c48b44-dd95-42e1-8c7b-f0112bc5e99e
		sourceLineageTag: TipoBoletim
		summarizeBy: none
		sourceColumn: TipoBoletim

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

	partition cotacoes = entity
		mode: directLake
		source
			entityName: cotacoes
			schemaName: dbo
			expressionSource: 'DirectLake - lake'

