table transacoes
	lineageTag: 3735cc50-134a-41b2-a1c0-67a07da9c2cb
	sourceLineageTag: [dbo].[transacoes]

	measure 'Valor Total' = SUM(transacoes[Total])
		formatString: 0.00
		displayFolder: Medidas
		lineageTag: d8151057-727e-4311-a2ca-be2b17073c08

		changedProperty = Name

		changedProperty = FormatString

		changedProperty = DisplayFolder

	measure 'Total R$' = ```
			
			SUMX(
			    moedas,
			    SUMX(
			        calendario,
			        COALESCE([Cotação corrigida], 1) * [Valor Total] 
			    )
			) 
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Medidas
		lineageTag: 04f540c6-41a6-4680-9710-f618946029b1

		changedProperty = Name

		changedProperty = FormatString

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column ID
		dataType: int64
		formatString: 0
		displayFolder: Colunas
		lineageTag: acf16131-02ae-4643-b08b-b46045b61dc5
		sourceLineageTag: ID
		summarizeBy: count
		sourceColumn: ID

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: Short Date
		displayFolder: Colunas
		lineageTag: a289e148-0546-4f37-a5a1-1f9a3a5f1a67
		sourceLineageTag: Data
		summarizeBy: none
		sourceColumn: Data

		changedProperty = FormatString

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

	column Total
		dataType: double
		displayFolder: Colunas
		lineageTag: bd600d40-8fd4-42f1-bb9f-72c22f5e0e0d
		sourceLineageTag: Total
		summarizeBy: sum
		sourceColumn: Total

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Moeda
		dataType: string
		displayFolder: Colunas
		lineageTag: 074c0e7d-d54a-45b3-baf0-8c5facc1ce9c
		sourceLineageTag: Moeda
		summarizeBy: none
		sourceColumn: Moeda

		changedProperty = DisplayFolder

		annotation SummarizationSetBy = Automatic

	partition transacoes = entity
		mode: directLake
		source
			entityName: transacoes
			schemaName: dbo
			expressionSource: 'DirectLake - lake'

